Fix missing getrawmonotonic() build error
When building with Linux version >= 5.6 we get following error:
```
mali_kbase_vinstr.c:905:2: error: implicit declaration of function ‘getrawmonotonic’ [-Werror=implicit-function-declaration]
  905 |  getrawmonotonic(&ts);
      |  ^~~~~~~~~~~~~~~
```
This is due to Linux commit:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=412c53a680a97cb1ae2c0ab60230e193bee86387
that removes getrawmonotonic(). So let's reimplement getrawmonotonic()
in mali_kbase.h that is included by many .c files, by using legacy code
when LINUX_VERSION_CODE >= 5.6.0.

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>