mali_kbase_defs.h: fix struct timespec incomplete type build error
When building with Linux version >= 5.6 we get following error:
```
mali_kbase_defs.h:759:18: error: field ‘timestamp’ has incomplete type
  759 |  struct timespec timestamp;
      |                  ^~~~~~~~~
```
This is due to Linux commit:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c766d1472c70d25ad475cf56042af1652e792b23
that hides 'struct timespec' to Kernel and Kernel module. So let's
reimplement it locally depending on LINUX_VERSION_CODE >= 5.6.0.

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>