mali_kbase_dma_fence: fix missing dma_resv_get_fences_rcu()
When building with Linux version >= 5.14 we get following error:
```
mali_kbase_dma_fence.c:248:8: error: implicit declaration of function ‘dma_resv_get_fences_rcu’; did you mean ‘dma_resv_get_fences’? [-Werror=implicit-function-declaration]
  248 |  err = dma_resv_get_fences_rcu(resv, &excl_fence, &shared_count,
      |        ^~~~~~~~~~~~~~~~~~~~~~~
      |        dma_resv_get_fences
```
This is due to Linux commit:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d3fae3b3daac09961ab871a25093b0ae404282d5
that drops _rcu suffix. So simply add locally a wrapper called
dma_resv_get_fences_rcu() that calls the actual dma_resv_get_fences() when
LINUX_VERSION_CODE >= 5.14.0.

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>