mali_kbase_softjobs: fix missing dma_buf_kmap/kunmap()
When building with Linux version >= 5.6 we get following error:
```
mali_kbase_softjobs.c:838:24: error: implicit declaration of function ‘dma_buf_kmap’; did you mean ‘dma_buf_vmap’? [-Werror=implicit-function-declaration]
  838 |    void *extres_page = dma_buf_kmap(dma_buf, i);
      |                        ^~~~~~~~~~~~
      |                        dma_buf_vmap
```
This is due to Linux commit:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7f0de8d80816d9620e995cf98acf4b6cd2d7c230
that removes dma_buf_kmap/kunamp(). But for having those functions to work,
we should need our driver to have dma_buf_ops->map/unmap initialized, but
this never happens, so basically dma_buf_kmap/kunamp() in this driver are
doing nothing. Then let's implement empty dma_buf_kmap/kunamp(), where the
first one always returns NULL, that way it fails and the driver ignore it
and doesn't call dma_buf_kunamp(). All this is done when
LINUX_VERSION_CODE >= 5.6.0.

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>