mali_kbase_jd/mem/mem_linux: fix building with Linux version >= 5.8.0
When building with Linux version >= 5.6 we get following error:
```
mali_kbase_mem.c:1035:36: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
 1035 |  lockdep_assert_held(&current->mm->mmap_sem);
```
This is due to Linux commit:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=da1c55f1b272f4bd54671d459b39ea7b54944ef9
that renames mmap_sem struct member to mmap_lock. So let's rename all those
members according to LINUX_VERSION_CODE >= 5.8.0.

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>