mali_kbase_sync.h: fix missing ksys_close() build error
When building with Linux version >= 5.11 we get following error:
```
mali_kbase_sync.h:170:2: error: implicit declaration of function ‘ksys_close’; did you mean ‘sys_close’? [-Werror=implicit-function-declaration]
  170 |  ksys_close(fd);
      |  ^~~~~~~~~~
      |  sys_close
```
This is due to Linux commit:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1572bfdf21d4d50e51941498ffe0b56c2289f783
that removes ksys_close() in favour of close_fd(). So let's reimplement
ksys_close() by using close_fd() like in the commit above when
LINUX_VERSION_CODE >= 5.11.0.

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>